#ifndef __KERNEL_CONFIG_H_
#define __KERNEL_CONFIG_H_

#ifndef MICROBLAZE_KERNEL
#define MICROBLAZE_KERNEL 1
#endif

#define NVME_KERNEL_MICROBLAZE 1
#define NVME_KERNEL_CORTEX_A53 0

#ifndef AUTO_FW_MGMT_BASE
#define AUTO_FW_MGMT_BASE 0x5000200000ULL
#endif

#ifndef AUTO_FW_MGMT_SIZE
#define AUTO_FW_MGMT_SIZE 0x0FE00000ULL
#endif

#ifndef AUTO_FW_DDR_BASE
#define AUTO_FW_DDR_BASE 0x5040000000ULL
#endif

#ifndef AUTO_FW_DDR_SIZE
#define AUTO_FW_DDR_SIZE (63ULL * 1024ULL * 1024ULL * 1024ULL)
#endif

#endif
