/* SPDX-License-Identifier: GPL-2.0 */
#ifndef NVME_FW_SSD_CONFIG_H
#define NVME_FW_SSD_CONFIG_H

#include <linux/device.h>
#include <linux/io.h>
#include <linux/types.h>

#define NVME_FW_SSD_PCIE_USER_CLOCK_HZ      250000000ULL
#define NVME_FW_SSD_NAND_CHANNELS           8U
#define NVME_FW_SSD_CHANNEL_BANDWIDTH_MBPS  1200ULL

#define NVME_FW_SSD_READ_LSB_NS             (35760ULL - 6000ULL)
#define NVME_FW_SSD_READ_MSB_NS             (35760ULL + 6000ULL)
#define NVME_FW_SSD_PROGRAM_NS              185000ULL
#define NVME_FW_SSD_FW_READ_NS              400ULL
#define NVME_FW_SSD_FW_WRITE_NS             800ULL
#define NVME_FW_SSD_CHANNEL_UNIT_BYTES      128ULL
#define NVME_FW_SSD_TRANSFER_BYTES          4096ULL

#define NVME_FW_SSD_DIV_ROUND_UP(n, d) \
	(((n) + (d) - 1ULL) / (d))
#define NVME_FW_SSD_NS_TO_CYCLES(ns) \
	NVME_FW_SSD_DIV_ROUND_UP((ns) * NVME_FW_SSD_PCIE_USER_CLOCK_HZ, \
				 1000000000ULL)
#define NVME_FW_SSD_CHANNEL_BYTES_PER_SEC \
	(NVME_FW_SSD_CHANNEL_BANDWIDTH_MBPS * 1024ULL * 1024ULL)
#define NVME_FW_SSD_CHANNEL_UNIT_NS \
	((NVME_FW_SSD_CHANNEL_UNIT_BYTES * 1000000000ULL) / \
	 NVME_FW_SSD_CHANNEL_BYTES_PER_SEC)
#define NVME_FW_SSD_CHANNEL_TRANSFER_UNITS \
	NVME_FW_SSD_DIV_ROUND_UP(NVME_FW_SSD_TRANSFER_BYTES, \
				 NVME_FW_SSD_CHANNEL_UNIT_BYTES)
#define NVME_FW_SSD_CHANNEL_TRANSFER_NS \
	(NVME_FW_SSD_CHANNEL_UNIT_NS * NVME_FW_SSD_CHANNEL_TRANSFER_UNITS)

#define NVME_FW_SSD_READ_LSB_CYCLES_DEFAULT \
	((u32)NVME_FW_SSD_NS_TO_CYCLES(NVME_FW_SSD_READ_LSB_NS))
#define NVME_FW_SSD_READ_MSB_CYCLES_DEFAULT \
	((u32)NVME_FW_SSD_NS_TO_CYCLES(NVME_FW_SSD_READ_MSB_NS))
#define NVME_FW_SSD_PROGRAM_CYCLES_DEFAULT \
	((u32)NVME_FW_SSD_NS_TO_CYCLES(NVME_FW_SSD_PROGRAM_NS))
#define NVME_FW_SSD_FW_READ_CYCLES_DEFAULT \
	((u32)NVME_FW_SSD_NS_TO_CYCLES(NVME_FW_SSD_FW_READ_NS))
#define NVME_FW_SSD_FW_WRITE_CYCLES_DEFAULT \
	((u32)NVME_FW_SSD_NS_TO_CYCLES(NVME_FW_SSD_FW_WRITE_NS))
#define NVME_FW_SSD_CH_XFER_4K_CYCLES_DEFAULT \
	((u32)NVME_FW_SSD_NS_TO_CYCLES(NVME_FW_SSD_CHANNEL_TRANSFER_NS))

void nvme_fw_ssd_reset(void __iomem *bar2);
void nvme_fw_ssd_apply(void __iomem *bar2, struct device *dev);
void nvme_fw_ssd_log(struct device *dev);

#endif
